name: Sync Docs to Wiki
on:
    push:
        branches: [ main ]
        # paths: [ "docs/**" ]

jobs:
  generate-and-push-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: jdhuyck/fantasy-lang-generator.wiki
          path: wiki-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Merge markdown files
        run: |
          python scripts/merge_wiki.py
          echo "Generated files:"
          ls -la wiki/

      - name: Debug remote
        run: git remote -v

      - name: Sync to Wiki
        env:
          WIKI_PUSH_TOKEN: ${{ secrets.WIKI_PUSH_TOKEN }}
        run: |
          cp wiki/* wiki-repo/
          cd wiki-repo
          git remote set-url origin https://${{ github.actor }}:$WIKI_PUSH_TOKEN@github.com/jdhuyck/fantasy-lang-generator.wiki.git

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update wiki for docs ($(date + '%Y-%m-%d %H:%M:%S'))"
            git push
          fi

      - name: Verify wiki update
        run: |
          echo "Wiki was successfully updated:"
          echo "https://github.com/jdhuyck/fantasy-lang-generator/wiki"